### ISSUE TITLE
Weird behavior of Runner

### ISSUE THREAD

**Issue by AitorATuin** [gobolinux/Scripts#21] opened 2017-05-07 20:42 UTC
While debugging another problem i found the following:

```
❯ ls -la /Programs/Scripts
total 28
drwxr-xr-x   5 root  root   4096 may  7 22:36 .
drwxr-xr-x 347 root  root  12288 may  7 22:36 ..
drwxr-xr-x   9 atuin atuin  4096 may  7 22:22 016.01
lrwxrwxrwx   1 root  root      3 may  7 22:29 Current -> git
drwxr-xr-x  11 atuin atuin  4096 mar 15 22:16 git
drwxrwxr-x   4 root  root   4096 dic  7 18:33 Settings

❯ Compile Ranger
Compile: Locating a recipe for Ranger ...
Compile: Found recipe for Ranger
GetRecipe: Trying to get /Data/Compile/LocalRecipes/Ranger/1.8.1
Compile: Recipe placed in /Data/Compile/LocalRecipes/Ranger/1.8.1
Compile: Checking dependencies...
Compile: Compiling Ranger version 1.8.1.
Runner -q -d /Data/Compile/LocalRecipes/Ranger/1.8.1/Resources/Dependencies /usr/bin/Compile --symlink=no --no-dependencies Ranger
/usr/bin/Compile: línea 9: ScriptFunctions: No existe el fichero o el directorio
/usr/bin/Compile: línea 10: Import: no se encontró la orden
/usr/bin/Compile: línea 11: Import: no se encontró la orden
[...]
```

It works perfectly after removing the 016.01 version from /Programs/Scripts

**Comment by lucasvr** [comment] 2017-05-07 21:29
Hisham has spotted this problem a few weeks ago, and so did I long ago. However, I thought that this was long gone. It's interesting, because I had Scripts 016 installed next to 016-GIT and the problem didn't happen. I can reproduce it when 016.01 is installed, though -- thanks a lot for adding this piece of information to your note.

By spawning Runner with `"-vv"` I can see that 016.01 is being picked up as the "most recent version" of Scripts, which causes 016-GIT to be removed from the overlay:

`adding dependency at /Programs/Scripts/016.01`

I'll work on a fix for this problem tonight.

**Closed** 2017-05-08 02:51 UTC
